{% set name = "PyTurboJPEG" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7d9625bbb2121b923228fc70d0c2b010b386687501f5b50acec4501222e152b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - libjpeg-turbo

test:
  requires:
    - requests
    - python {{ python_min }}

about:
  home: https://github.com/lilohuang/PyTurboJPEG/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  doc_url: https://github.com/lilohuang/PyTurboJPEG/
  dev_url: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
