{% set name = "PyTurboJPEG" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5cee57de33a3d717a091dc9b4b8b534f993c046ebbfd2a1d64bdd0d06ec92e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - numpy
    - libjpeg-turbo

test:
  requires:
    - requests

about:
  home: https://github.com/lilohuang/PyTurboJPEG/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  doc_url: https://github.com/lilohuang/PyTurboJPEG/
  dev_url: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
