schema_version: 1

context:
  name: PyTurboJPEG
  version: "2.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: 43fdcf281b7e3a4424ad0e5107225da207c29c08d8d7d8b096a79390257d9dfd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - libjpeg-turbo

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - requests
    script:
      interpreter: python
      file: run_test.py


about:
  license: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  homepage: https://github.com/lilohuang/PyTurboJPEG/
  repository: https://github.com/lilohuang/PyTurboJPEG/
  documentation: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
